### PR TITLE
relax restriction Fab

### PR DESCRIPTION
**Pull request by eltjo-k**

### CODE REVIEW

**Comment by javierpardollama** [comment]
Should not we update the Package Json as well?

**Review by javierpardollama — APPROVED** [review]
Do not forget to increase the versioning

**Review by xaberue — CHANGES_REQUESTED** [review]
Wait for finishing in release 1

**Comment by cotecna-itpi-admin** [comment]
Hi @eltjo-k , I'll prefer to discard this PR since I'll prefer to properly document and keep a track in version1release, and then merge what was done in this branch, to main.

**Pull request closed without merging**
